# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='libro',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
